name: merge check workflow

on:
  push:
    branches: [ main ]

jobs:

  push-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # configure binaries
      - name: Configure Binaries
        uses: hashicorp/packer-github-actions@master
        with:
          command: init

      # build artifacts
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          PACKER_LOG: 1
        with:
          command: build
          target: .
